### ISSUE TITLE
doesn't start the server and logs PANIC

### ISSUE THREAD

**Issue by Tapudp** [bruno-chavez/restedancestor#3]
After cloning the project and running the `go run main.go` it just simply logs out 

```
panic: open ..C:\Users\Divyesh\go/src/github.com/bruno-chavez/restedancestor/database/database.json: The filename, directory name, or volume label syntax is
incorrect.

goroutine 1 [running]:
github.com/bruno-chavez/restedancestor/database.Parser(0x1d, 0x70b020, 0xc04203c1c0)
        C:/Go/src/github.com/bruno-chavez/restedancestor/database/database.go:53 +0x353
exit status 2
```

**Comment by bruno-chavez** [comment]
Hi there, currently restedancestor doesn't support Windows and wont until i find a solution about how to use the json data without the binary trying to red the json file, will update the readme accordingly.

**Comment by Tapudp** [comment]
ahh okay Thank you then my chances of creating new routes for the REST api are not there. I have learned the GoLang because of you though. Thank you so much brother, I would love to work on any future projects. 

Thanks again.
